//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace PowerNew.DoWork {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IMyBjfService", Namespace="http://tempuri.org/")]
    public partial class MyBjfService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoWorkOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MyBjfService() {
            this.Url = global::PowerNew.Properties.Settings.Default.PowerNew_DoWork_MyBjfService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DoWorkCompletedEventHandler DoWorkCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IMyBjfService/DoWork", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
        public bjf_block[] DoWork() {
            object[] results = this.Invoke("DoWork", new object[0]);
            return ((bjf_block[])(results[0]));
        }
        
        /// <remarks/>
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        /// <remarks/>
        public void DoWorkAsync(object userState) {
            if ((this.DoWorkOperationCompleted == null)) {
                this.DoWorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoWorkOperationCompleted);
            }
            this.InvokeAsync("DoWork", new object[0], this.DoWorkOperationCompleted, userState);
        }
        
        private void OnDoWorkOperationCompleted(object arg) {
            if ((this.DoWorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoWorkCompleted(this, new DoWorkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1590.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/WcfService1")]
    public partial class bjf_block {
        
        private string blocknameField;
        
        private int createidField;
        
        private bool createidFieldSpecified;
        
        private System.DateTime createtimeField;
        
        private bool createtimeFieldSpecified;
        
        private System.Nullable<System.DateTime> deletetimeField;
        
        private bool deletetimeFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private bool isdeleteField;
        
        private bool isdeleteFieldSpecified;
        
        private int isuseField;
        
        private bool isuseFieldSpecified;
        
        private int sortcodeField;
        
        private bool sortcodeFieldSpecified;
        
        private int updateidField;
        
        private bool updateidFieldSpecified;
        
        private System.DateTime updatetimeField;
        
        private bool updatetimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string blockname {
            get {
                return this.blocknameField;
            }
            set {
                this.blocknameField = value;
            }
        }
        
        /// <remarks/>
        public int createid {
            get {
                return this.createidField;
            }
            set {
                this.createidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createidSpecified {
            get {
                return this.createidFieldSpecified;
            }
            set {
                this.createidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime createtime {
            get {
                return this.createtimeField;
            }
            set {
                this.createtimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool createtimeSpecified {
            get {
                return this.createtimeFieldSpecified;
            }
            set {
                this.createtimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> deletetime {
            get {
                return this.deletetimeField;
            }
            set {
                this.deletetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletetimeSpecified {
            get {
                return this.deletetimeFieldSpecified;
            }
            set {
                this.deletetimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool isdelete {
            get {
                return this.isdeleteField;
            }
            set {
                this.isdeleteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isdeleteSpecified {
            get {
                return this.isdeleteFieldSpecified;
            }
            set {
                this.isdeleteFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int isuse {
            get {
                return this.isuseField;
            }
            set {
                this.isuseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isuseSpecified {
            get {
                return this.isuseFieldSpecified;
            }
            set {
                this.isuseFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int sortcode {
            get {
                return this.sortcodeField;
            }
            set {
                this.sortcodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sortcodeSpecified {
            get {
                return this.sortcodeFieldSpecified;
            }
            set {
                this.sortcodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int updateid {
            get {
                return this.updateidField;
            }
            set {
                this.updateidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updateidSpecified {
            get {
                return this.updateidFieldSpecified;
            }
            set {
                this.updateidFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime updatetime {
            get {
                return this.updatetimeField;
            }
            set {
                this.updatetimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool updatetimeSpecified {
            get {
                return this.updatetimeFieldSpecified;
            }
            set {
                this.updatetimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    public delegate void DoWorkCompletedEventHandler(object sender, DoWorkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1590.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DoWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bjf_block[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bjf_block[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591