//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerNew.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bjf_leavemessage
    {
        public int id { get; set; }
        public bool type { get; set; }
        public int parentid { get; set; }
        public string message { get; set; }
        public string position { get; set; }
        public System.DateTime createtime { get; set; }
        public string name { get; set; }
        public string browser { get; set; }
        public string ip { get; set; }
    }
}
