//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerNew.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bjf_account
    {
        public int id { get; set; }
        public string name { get; set; }
        public string mobile { get; set; }
        public string domainname { get; set; }
        public string domainshortname { get; set; }
        public string dbserver { get; set; }
        public string dbname { get; set; }
        public string dbuserid { get; set; }
        public string dbpassword { get; set; }
        public string comment { get; set; }
        public Nullable<int> state { get; set; }
        public int createid { get; set; }
        public System.DateTime createtime { get; set; }
        public int updateid { get; set; }
        public System.DateTime updatetime { get; set; }
        public bool isdelete { get; set; }
    }
}
