//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerNew.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class bjf_roleformenu
    {
        public int id { get; set; }
        public int roleid { get; set; }
        public int menuid { get; set; }
        public System.DateTime createtime { get; set; }
        public int createid { get; set; }
        public int updateid { get; set; }
        public System.DateTime updatetime { get; set; }
    }
}
