//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerNew.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class powerbjfEntities : DbContext
    {
        public powerbjfEntities()
            : base("name=powerbjfEntities")
        {
        }

        public powerbjfEntities(string conn)
            : base(conn)
        {

        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<bjf_account> bjf_account { get; set; }
        public virtual DbSet<bjf_article> bjf_article { get; set; }
        public virtual DbSet<bjf_block> bjf_block { get; set; }
        public virtual DbSet<bjf_loginlog> bjf_loginlog { get; set; }
        public virtual DbSet<bjf_menu> bjf_menu { get; set; }
        public virtual DbSet<bjf_role> bjf_role { get; set; }
        public virtual DbSet<bjf_roleformenu> bjf_roleformenu { get; set; }
        public virtual DbSet<bjf_roleforuser> bjf_roleforuser { get; set; }
        public virtual DbSet<bjf_user> bjf_user { get; set; }
        public virtual DbSet<bjf_articletype> bjf_articletype { get; set; }
        public virtual DbSet<bjf_articleinfo> bjf_articleinfo { get; set; }
        public virtual DbSet<bjf_leavemessage> bjf_leavemessage { get; set; }
    }
}
